defaults:
  - launcher: local
  - solver: cem
  - _self_

world:
  env_name: swm/OGBScene-v0
  num_envs: ${eval.num_eval}
  max_episode_steps: ??? # make sure it's >= eval_budget
  history_size: 1
  frame_skip: 1
  env_type: scene
  ob_type: states
  mode: task
  multiview: False
  width: 224
  height: 224
  visualize_info: False
  terminate_at_goal: True

dataset:
  stats: ${eval.dataset_name}
  keys_to_cache:
    - action

seed: 42
cache_dir: null
policy: random # ckpt name or random

plan_config:
  horizon: 5
  receding_horizon: 5
  action_block: 5 # frameskip

eval:
  num_eval: 50
  start_manifest: null
  goal_offset_steps: 25
  eval_budget: 50
  img_size: 224
  dataset_name: ogbench/scene_play_lewm_10k_200
  start_filter:
    mode: scene_goal_mismatch
    block_pos_tolerance: 0.04
    drawer_pos_tolerance: 0.04
    window_pos_tolerance: 0.04
  callables:
    - method: set_state
      args:
        qpos:
          value: qpos
        qvel:
          value: qvel
        button_states:
          value: button_states
    - method: set_goal_state
      args:
        target_pos:
          value: goal_privileged_block_0_pos
        target_quat:
          value: goal_privileged_block_0_quat
        target_button_states:
          value: goal_button_states
        target_drawer_pos:
          value: goal_privileged_drawer_pos
        target_window_pos:
          value: goal_privileged_window_pos

output:
  filename: ogb_scene_results.txt
  save_video: True
  save_structured: True
  structured_filename: null
